### ISSUE TITLE
It gives the list of pilots

### ISSUE THREAD

**Issue by julianrodes** [KJRDev/phpVMS_PilotLogins#1]
I installed as you say this addon, but the administration section you say to see the listing and not have any driver appears, and not recorded anything in the database, you say it's version 1.1, there is something else in version 1, which have not included in this version so is giving this error. Thank you

**Comment by Vansers** [comment]
Hey,

In the database, the table for this add-on should be pilotlogins, if it says phpvms_pilotlogins, please run the following query... 

RENAME TABLE phpvms_pilotlogins TO pilotlogins

In the Admin area, you should be seeing a link to the module, check in the Add-Ons tab on the left side.

If you are still having issues after trying these solutions, let me know.

Cheers! ;)

**Comment by julianrodes** [comment]
Well first thank you for answer and tell you in this database table with
the correct name "pilotlogins". In Admin area, if the link to view the list
appears, but as you will see I attached two screenshots for you to see and
be seen, likewise I attached the files as download them if you see any
error, I I have reviewed, but I'm not an advanced programmer and at first
sight I have not seen anything strange.
Thanks for your time and I hope your answer

Best regards

2014-10-18 15:33 GMT+02:00 Kyle notifications@github.com:

> Hey,
> 
> In the database, the table for this add-on should be pilotlogins, if it
> says phpvms_pilotlogins, please run the following query...
> 
> RENAME TABLE phpvms_pilotlogins TO pilotlogins
> 
> In the Admin area, you should be seeing a link to the module, check in the
> Add-Ons tab on the left side.
> 
> If you are still having issues after trying these solutions, let me know.
> 
> Cheers! ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Vansers/phpVMS_PilotLogins/issues/1#issuecomment-59613127
> .

## 

Julian Rodriguez

Correo: julianrodes@gmail.com

Por favor tenga en cuenta su responsabilidad ambiental antes de
imprimir este correo.
Por favor tenha em conta a sua responsabilidade ambiental antes de
imprimir esta mensagem.
Please consider the environment before printing this e-mail.
Este mensaje puede contener información confidencial, por lo que está
prohibida la copia, el uso o la distribución no autorizada de la misma.
Si usted no es el destinatario del mensaje, le rogamos que lo notifique al
remitente y que lo destruya junto con todo su contenido. Gracias.
P Seamos responsables con el medioambiente, no imprimir el correo sino es
necesario

**Comment by Vansers** [comment]
Hey,

I don't see any of the attachments here on Github. Can you upload it to an image site such as http://tinypic.com ?

Thanks!

**Comment by julianrodes** [comment]
Hi, see if you can see them now doubtfully me out 
Thanks

http://prntscr.com/4xfslp

http://prntscr.com/4xfsj5

**Comment by Vansers** [comment]
On http://forum.phpvms.net/topic/5768-pilotlogins-v10/

Did you do How to Install #5 step, adding the code into your Login.php?
